wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1650947650
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      4: 3.7.13
      5: 0.12.15
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 512
doodle_channel_list:
  desc: null
  value:
  - 64
  - 128
  - 256
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.02
real_channel_list:
  desc: null
  value:
  - 64
  - 128
  - 256
