wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1650953375
    t:
      1:
      - 1
      - 41
      - 55
      4: 3.7.13
      5: 0.12.15
      8:
      - 1
      - 5
